home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='login'),
    
]

libre_eps/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', include('start.urls')),
    path('of/', include('office.urls')),
]

office/urls.py
from django.urls import path
from . import views

app_name = 'office' 

urlpatterns = [
    path('p/    ', views.profile, name='profile'),
    path('a/', views.authorizations, name='authorizations'),
    path('ya/', views.authorized, name='authorized'),
    path('na/', views.new_auth, name='new_auth'),
    path('c/', views.certifications, name='certifications'),
    path('mq/', views.module_quotes, name='module_quotes'),
    path('q/', views.quotes, name='quotes'),
    path('aq/', views.available_quotes, name='available_quotes'),
    path('cq/', views.created_quotes, name='created_quotes'),
    path('pe/', views.personal, name='personal'),
    path('logout/', views.log_out, name='logout'),
    path('pqr/', views.pqr, name='pqr')
]

office/models.py
import random
from django.db import models
import uuid
from datetime import datetime
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator, RegexValidator
from datetime import date
from choices import *

class Petition(models.Model):

    number = models.AutoField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(auto_now=True)
    status = models.CharField(max_length=100)
    comments = models.TextField()  
    response = models.TextField()
    hc_file = models.FileField(upload_to='attached_files/', null=True, blank=False)
    or_file = models.FileField(upload_to='attached_files/', null=True, blank=False)
    def save(self, *args, **kwargs):
        
        if not self.request_number:
            self.request_number = random.randint(100000, 999999)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Petition #{self.number}"
    
class Authorization(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    ips = models.CharField(max_length=255)
    b_date = models.DateField()
    e_date = models.DateField()
    auth_file = models.FileField(upload_to='authorization_file/')

    auth_file = models.FileField(
        upload_to='authorization_file/',
        validators=[FileExtensionValidator(allowed_extensions=['pdf'])]
    )

    def __str__(self):
        return f'Autorización de {self.name} para {self.ips} ({self.b_date} a {self.e_date})'

class Quote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    ips = models.CharField(max_length=255)
    doctor = models.CharField(max_length=255)
    date = models.DateField()
    hour = models.TimeField()
    instructions = models.BooleanField(default=False, help_text='Marcar para no permitir nuevas citas')
    available = models.BooleanField(default=True, help_text='Marcar para indicar que la cita está disponible')

    def __str__(self):
        return f"Cita para {self.user.user} con el Dr. {self.doctor} el {self.date} a las {self.hour}"

class AvailableQuote(models.Model):
    ips = models.CharField(max_length=255)
    doctor = models.CharField(max_length=255)
    date = models.DateField()
    hour = models.TimeField()
    instructions = models.BooleanField(default=False, help_text='Marcar para no permitir nuevas citas')
    available = models.BooleanField(default=True, help_text='Marcar para indicar que la cita está disponible')

    def __str__(self):
        return f"Cita disponible con el Dr. {self.doctor} el {self.date} a las {self.hour}"

class CreatedQuote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    especialidad = models.CharField(max_length=255)
    ips = models.CharField(max_length=255)
    doctor = models.CharField(max_length=255)
    date = models.DateField()
    hour = models.TimeField()
    instructions = models.BooleanField(default=False, help_text='Marcar para no permitir nuevas citas')
    available = models.BooleanField(default=True, help_text='Marcar para indicar que la cita está disponible')

    def __str__(self):
        return f"Cita pendiente con el Dr. {self.doctor} el {self.date} a las {self.hour}"
    


class Pqrs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField('Nombre completo', max_length=50, null=False)
    card_type = models.CharField('Tipo de documento', choices=CARD_TYPE, max_length=22, null=False, blank=False)
    card_number = models.CharField('Número de documento', max_length=10, default='0', null=False, validators=[RegexValidator(regex='^[0-9]{10}$')])
    gender = models.CharField('Género', choices=GENDER, max_length=9, null=False)
    birth_date = models.DateField('Fecha de nacimiento', default=date(2000, 1, 1), null=False)
    
    cell_phone = models.CharField('Celular', max_length=10, null=False, blank=False, validators=[RegexValidator(regex='^[0-9]{10}$')])
    phone = models.CharField('Teléfono', max_length=10, null=False, blank=True, validators=[RegexValidator(regex='^[0-9]{10}$')])
    email = models.EmailField('Correo electrónico', unique=True, null=False, blank=False)
    
    def __str__(self):
        return self.card_number
    
    
    
    REQUIRED_FIELDS = ['first_name',  'card_type', 'card_number',  'gender', 'birth_date', 'cell_phone', 'email']

office/forms.py
from django import forms
from .models import Petition, Quote, CreatedQuote, Pqrs

class PetitionForm(forms.ModelForm):
    class Meta:
        model = Petition
        fields = ['hc_file', 'or_file', 'comments']

    def clean(self):
        cleaned_data = super().clean()
        hc_file = cleaned_data.get('hc_file')
        or_file = cleaned_data.get('or_file')

        if not hc_file and not or_file:
            raise forms.ValidationError('Debes adjuntar al menos un archivo.')

        return cleaned_data


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['ips', 'doctor', 'date', 'hour', 'instructions']

class CreatedQuoteForm(forms.ModelForm):
    class Meta:
        model = CreatedQuote
        fields = ['especialidad', 'ips', 'doctor', 'date', 'hour']


class PqrsForm(forms.ModelForm):
    class Meta:
        model = Pqrs
        fields = ['first_name', 'card_type', 'card_number', 'gender', 'birth_date', 'cell_phone', 'phone', 'email']

office/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from datetime import datetime
import uuid
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .models import CreatedQuote 
from datetime import datetime

@login_required
def profile(request):
    return render(request, 'profile.html')

@login_required
def authorizations(request):
    return render(request, 'authorizations.html')

@login_required
def certifications(request):
    return render(request, 'certifications.html')
@login_required
def created_quotes(request):
    if request.method == 'POST':
        especialidad = 'Medicina General'
        doctor = request.POST.get('doctor')
        date_str = request.POST.get('date')
        hour_str = request.POST.get('hour')
        ips = request.POST.get('ips')

        print("Datos del formulario:")
        print(f"Doctor: {doctor}, Fecha: {date_str}, Hora: {hour_str}, IPS: {ips}")

        # Convertir la cadena de fecha al formato correcto
        date = datetime.strptime(date_str, '%b. %d, %Y').strftime('%Y-%m-%d')
        try:
            hour = datetime.strptime(hour_str, '%I:%M %p').strftime('%H:%M')
        except ValueError:
            # Manejar el caso en que la cadena de hora no tiene el formato esperado
            # Puedes agregar lógica adicional aquí según tus requisitos
            hour = None

        # Verificar si la hora se pudo convertir correctamente
        if hour is not None:
            # Crea la cita agendada en la nueva tabla
            created_quote = CreatedQuote.objects.create(
                especialidad=especialidad,
                ips=ips,
                doctor=doctor,
                date=date,
                hour=hour,
                
            )
            created_quote.save()

            print("Cita creada:", created_quote)

        created_quotes = CreatedQuote.objects.all()
        
    print("Citas agendadas:", created_quotes)

    available_quotes = []  # Asegúrate de obtener las citas disponibles de alguna manera

    return render(request, 'quotes.html', {'created_quotes': created_quotes, 'available_quotes': available_quotes})

@login_required
def available_quotes(request):
    created_quotes = CreatedQuote.objects.all().filter(available=True)
    available_quotes = AvailableQuote.objects.filter(available=True)
    return render(request, 'quotes.html', {'created_quotes': created_quotes,'available_quotes': available_quotes})

def module_quotes(request):
    created_quotes = CreatedQuote.objects.all()
    return render(request, 'quotes.html', {'created_quotes': created_quotes})

def quotes(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user  # Asigna el usuario actual a la cita
            quote.save()
            messages.success(request, 'Cita creada exitosamente.')
            return redirect('quotes')  # Redirige a la misma página después de crear la cita
        else:
            messages.error(request, 'Error en el formulario. Por favor, corrige los errores.')
    else:
        form = QuoteForm()

    return render(request, 'quotes.html', {'form': form})

@login_required
def personal(request):
    return render(request, 'personal.html')

@login_required
def authorized(request):
    
    user_authorizations = Authorization.objects.all()

    context = {
        'authorization': user_authorizations,
    }

    return render(request, 'authorized.html', context)

@login_required
def new_auth(request):
    if request.method == 'POST':
        form = PetitionForm(request.POST, request.FILES)

        if form.is_valid():
            petition = form.save(commit=False)
            petition.id = uuid.uuid4()  
            petition.date = datetime.now()
            petition.save()
            return redirect('new_auth')  
    else:
        form = PetitionForm()

    return render(request, 'new_auth.html', {'form': form})

@login_required
def log_out(request):
    logout(request)
    return redirect('index')

def pqr(request):
    if request.method == 'POST':
        form = PqrsForm(request.POST)
        if form.is_valid():
            form.save()
            # Agrega lógica adicional según tus necesidades
            return redirect('gracias')
    else:
        form = PqrsForm()

    return render(request, 'pqr.html', {'form': form})

office/templates/authorizations.html
{% extends "base.html" %}
{% load static %}
{% block title %}Autorizaciones{% endblock %}

{% block content %}
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
        <h1 class="logo me-auto"><a href="{% url 'index' %}">Libre EPS</a></h1>
        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="nav-link scrollto active" href="{% url 'office:profile' %}">Inicio</a></li>
            <li><a class="nav-link scrollto" href="{% url 'office:quotes' %}">Citas médicas</a></li>
            <li class="dropdown"><a href="#contact"><span>Canales de atención</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'office:pqr' %}">Registrar PQRS</a></li>
                <li><a href="#">Contáctenos</a></li>
              </ul>
            </li>          
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        {% if user.is_authenticated %}
            <div class="ms-auto" style="display: flex; flex-direction: column; align-items: flex-end;">          
                <h1 class="logo " id="page-title"><a>Usuario: Julian Acosta</a></h1>
                <a href="{% url 'office:logout' %}" style="text-decoration: none; color: #0474cc; margin-bottom: 5px;">Cerrar sesión</a>
                
            </div>
        {% else %}
            <h1 class="logo ms-auto" id="page-title"><a href="{% url 'login' %}">Iniciar sesión</a></h1>
        {% endif %}
    </div>
  </header>
<br><br><br>
<style>
    @media (max-width: 992px) {
  .col-lg-4 {
    flex:   auto;
    width: 100%;
  }
}
body{
        background-color: rgba(25, 119, 204, 0.2);
        /*background-color: #f1f7fd;*/
    }
  </style>
<section id="services_"  class="services">
<div class="container text-center ">
        <div class="row ">
            <div class="custom-row" style="display: flex;justify-content: space-around;flex-direction: row;">
                <div class="col-lg-4 col-md-6 align-items-stretch mt-4 ">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-hospital-user"></i></div>
                        <h4><a href="{% url 'office:new_auth' %}">Solicitar autorizaciones</a></h4>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 align-items-stretch mt-4 ">
                    <div class="icon-box">
                        <div class="icon"><i class="fas fa-hospital-user"></i></div>
                        <h4><a href="{% url 'office:authorized' %}">Consultar autorizaciones</a></h4>
                    </div>
                </div>
            </div>
        </div>
</div>
</section>

{% endblock %}

office/templates/authorized.html
{% extends "base.html" %}
{% load static %}
{% block title %}Autorizaciones{% endblock %}

{% block content %}
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
        <h1 class="logo me-auto"><a href="{% url 'index' %}">Libre EPS</a></h1>
        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="nav-link scrollto active" href="{% url 'office:profile' %}">Inicio</a></li>
            <li><a class="nav-link scrollto" href="{% url 'office:authorizations' %}">Autorizaciones</a></li>
            <li><a class="nav-link scrollto" href="{% url 'office:quotes' %}">Citas médicas</a></li>
            <li class="dropdown"><a href="#contact"><span>Canales de atención</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a  href="{% url 'office:pqr' %}">Registrar PQRS</a></li>
                <li><a href="#">Contáctenos</a></li>
              </ul>
            </li>          
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        {% if user.is_authenticated %}
            <div class="ms-auto" style="display: flex; flex-direction: column; align-items: flex-end;">          
                <h1 class="logo " id="page-title"><a>Usuario: Julian Acosta</a></h1>
                <a href="{% url 'office:logout' %}" style="text-decoration: none; color: #0474cc; margin-bottom: 5px;">Cerrar sesión</a>
                
            </div>
        {% else %}
            <h1 class="logo ms-auto" id="page-title"><a href="{% url 'login' %}">Iniciar sesión</a></h1>
        {% endif %}
    </div>
  </header>
<br><br><br>
<style>
    @media (max-width: 992px) {
        .col-lg-4 {
            flex: auto;
            width: 100%;
        }
    }

    body {
        background-color: rgba(25, 119, 204, 0.2);
        /*background-color: #f1f7fd;*/
    }



    .table-primary th {
        background-color: #0474cc !important;
        color: #fff;
    }
</style>

<div class="container mt-4">
    <br><br>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="table-primary">
                <tr>
                    <th>Nombre</th>
                    <th>Prestador</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Final</th>
                    <th>Autorización</th>
                </tr>
            </thead>
            <tbody>
                {% for authorization in authorizations %}
                <tr>
                    <td>{{ authorization.name }}</td>
                    <td>{{ authorization.ips }}</td>
                    <td>{{ authorization.b_date }}</td>
                    <td>{{ authorization.e_date }}</td>
                    <td>
                        <a href="{{ authorization.auth_file.url }}" download>Descargar</a>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td>ACETAMINOFEN 500MG + PROZAC 65MG</td>
                    <td>CRUZ VERDE</td>
                    <td>2023-12-01</td>
                    <td>2024-01-01</td>
                    <td>
                        <a href="{% static 'ruta/a/otro/archivo.pdf' %}" target="_blank">Ver PDF</a>
                    </td>
                </tr>
                <!-- Agrega más filas según tus datos -->
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

office/templates/certifications.html
{% extends "base.html" %}
{% load static %}
{% block title %}Certificaciones{% endblock %}

{% block content %}
    <form action="../index.html">
        <input type="submit" value="Back">
    </form>
    <form action="login.html">
        <input type="submit" value="Exit">
    </form>
    <h1>Certifications</h1>
    <p>Here you can get whatever you need about your certifications</p>
    {% endblock %}

office/templates/new_auth.html
{% extends "base.html" %}
{% load static %}
{% block title %}Autorizaciones{% endblock %}

{% block content %}

<header id="header" class="fixed-top">
  <div class="container d-flex align-items-center">
      <h1 class="logo me-auto"><a href="{% url 'index' %}">Libre EPS</a></h1>
      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'office:profile' %}">Inicio</a></li>
          
          <li><a class="nav-link scrollto" href="{% url 'office:quotes' %}">Citas médicas</a></li>
          <li class="dropdown"><a href="#contact"><span>Canales de atención</span> <i class="bi bi-chevron-right"></i></a>
            <ul>
              <li><a  href="{% url 'office:pqr' %}">Registrar PQRS</a></li>
              <li><a href="#">Contáctenos</a></li>
            </ul>
          </li>          
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
      {% if user.is_authenticated %}
          <div class="ms-auto" style="display: flex; flex-direction: column; align-items: flex-end;">          
              <h1 class="logo " id="page-title"><a>Usuario: Julian Acosta</a></h1>
              <a href="{% url 'office:logout' %}" style="text-decoration: none; color: #0474cc; margin-bottom: 5px;">Cerrar sesión</a>
              
          </div>
      {% else %}
          <h1 class="logo ms-auto" id="page-title"><a href="{% url 'login' %}">Iniciar sesión</a></h1>
      {% endif %}
  </div>
</header>
<br><br><br><br><br><br>
<style>
  /* Estilos personalizados */
  .custom-tab {
    background-color: #0474cc;
    color: #fff;
  }

  .custom-tab:hover {
    background-color: rgba(25, 119, 204, 0.2);
    color: #000;
  }

  .custom-tab.active {
    background-color: #0474cc;
    color: #fff;
  }

  @media (max-width: 992px) {
    .col-lg-4 {
      flex: auto;
      width: 100%;
    }
  }

  body {
    background-color: rgba(25, 119, 204, 0.2);
    /*background-color: #f1f7fd;*/
  }


  .table-primary th {
    background-color: #0474cc !important;
    color: #fff;
  }
</style>
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active custom-tab" id="solicitar-tab" data-bs-toggle="tab" href="#solicitar">Solicitar</a>
    </li>
    <li class="nav-item">
      <a class="nav-link custom-tab" id="consultar-tab" data-bs-toggle="tab" href="#consultar">Consultar Solicitudes</a>
    </li>
  </ul>

  <div class="tab-content">
    <!-- Solicitar -->
    <div id="solicitar" class="tab-pane active">
      <br><br>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            <div class="mb-3">
              <label for="campoTexto" class="form-label">Observaciones<span class="text-danger">*</span>:</label>
              <textarea type="text" class="form-control" id="campoTexto" required rows="8"></textarea>
            </div>
          </div>

          <div class="col-md-6">
            <!-- HC-->
            <div class="mb-3">
              <label class="form-label">Adjuntar Historia Clínica (JPG o PDF)<span class="text-danger">*</span>:</label>
              <input type="file" class="form-control">
            </div>

            <!-- OR -->
            <div class="mb-3">
              <label class="form-label">Adjuntar Órdenes (JPG o PDF):<span class="text-danger">*</span></label>
              <input type="file" class="form-control">
            </div>
            <div class="text-center">
              <button type="submit" class="btn custom-btn" style="height: auto; background-color: #0474cc; color: #fff;"
                >Enviar</button>
            </div>
          </div>
        </div>
      </form>

    </div>

    <!--Consultar Solicitudes -->
    <div id="consultar" class="tab-pane">
      <br><br>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead class="table-primary">
            <tr>
              <th>Número de Solicitud</th>
              <th>Fecha de Solicitud</th>
              <th>Estado</th>
              <th>Observaciones de Usuario</th>
              <th>Respuesta</th>
            </tr>
          </thead>
          <tbody>
            {% for petition in petitions %}
            <tr>
              <td>{{ petition.code }}</td>
              <td>{{ petition.date }}</td>
              <td>{{ petition.status }}</td>
              <td>{{ petition.comments }}</td>
              <td>{{ petition.response }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

office/templates/personal.html
{% extends "base.html" %}
{% load static %}
{% block title %}Oficina{% endblock %}

{% block content %}
    <form action="../index.html">
        <input type="submit" value="Back">
    </form>
    <form action="login.html">
        <input type="submit" value="Exit">
    </form>
    <h1>Personal Information</h1>
    <p>Here you can get whatever you need about your personal infomrmation.</p>
    {% endblock %}

office/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Oficina{% endblock %}

{% block content %}
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
        <h1 class="logo me-auto"><a href="{% url 'index' %}">Libre EPS</a></h1>
        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="nav-link scrollto active" href="{% url 'office:profile' %}">Noticias</a></li>
            
            <li class="dropdown"><a href="#contact"><span>Canales de atención</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a  href="{% url 'office:pqr' %}">Registrar PQRS</a></li>
                <li><a href="#">Contáctenos</a></li>
              </ul>
            </li>          
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        {% if user.is_authenticated %}
            <div class="ms-auto" style="display: flex; flex-direction: column; align-items: flex-end;">          
                <h1 class="logo " id="page-title"><a>Usuario: Julian Acosta</a></h1>
                <a href="{% url 'office:logout' %}" style="text-decoration: none; color: #0474cc; margin-bottom: 5px;">Cerrar sesión</a>
                
            </div>
        {% else %}
            <h1 class="logo ms-auto" id="page-title"><a href="{% url 'login' %}">Iniciar sesión</a></h1>
        {% endif %}
    </div>
  </header>


<br>
<style>
    @media (max-width: 992px) {
        .col-lg-4 {
            flex: auto;
            width: 70%;
        }
    }
    body{
        background-color: rgba(25, 119, 204, 0.2);
        /*background-color: #f1f7fd;*/
    }
</style>
<section id="services_" class="services" style="
display: flex;
align-items: center;
justify-content: center;
height: 900px;
">
    <div class="container">
        <div class="add_options_profile">

        </div>

        <!--<div class="section-title">
            <h2>Servicios</h2>
            <p>Gestiona tus citas médicas, autorizaciones, certificaciones y más</p>
        </div>-->

        <div class="custom-row" style="
        display: inline-flex;
        justify-content: center;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: stretch;
    ">
            <div class="col-lg-4 col-md-6  align-items-stretch mt-lg-0" >
                <div class="icon-box">
                    <div class="icon"><i class="fas fa-pills"></i></div>
                    <h4><a href="{% url 'office:authorizations' %}">Autorizaciones</a></h4>
                    <p>Consulte, renueve y genere sus autorizaciones</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 align-items-stretch mt-4 mt-lg-0">
                <div class="icon-box">
                    <div class="icon"><i class="fas fa-heartbeat"></i></div>
                    <h4><a href="{% url 'office:module_quotes' %}">Citas médicas</a></h4>
                    <p>Agende, reprograme o cancele sus citas</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 align-items-stretch mt-4 mt-lg-0">
                <div class="icon-box">
                    <div class="icon"><i class="fas fa-hospital-user"></i></div>
                    <h4><a href="{% url 'office:personal' %}">Información personal</a></h4>
                    <p>Actualice su informacion personal y de contacto</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 align-items-stretch mt-4 mt-lg-0">
                <div class="icon-box">
                    <div class="icon"><i class="fas fa-hospital-user"></i></div>
                    <h4><a href="{% url 'office:module_quotes' %}">Historia clínica</a></h4>
                    <p>Historias clínicas generadas por Libre EPS</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 align-items-stretch mt-4 mt-lg-0">
                <div class="icon-box">
                    <div class="icon"><i class="fas fa-notes-medical"></i></div>
                    <h4><a href="{% url 'office:certifications' %}">Certificaciones</a></h4>
                    <p>Certificados de afiliación, pagos e incapacidades</p>
                </div>
            </div>

        </div>

    </div>
</section><!-- End Services Section -->
{% endblock %}